---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgDXWrQgNK8Rp72JQFSY2IvniOTQ0G7lG2oBhroWAiaHyh14YLYIJiBBSi3Rc1g7EZSvYOuCU9Pe9SV29fkidSF+sFzE4yFyZ0fTyxc4Zv80cO83H/YXP1GpOwXSednZXzdwFWA5XoDP405dysluAxq7oOTst/9Sppy9uLSuEMre560zp9Y/rv/BGqLW0scPWthCG42PkICx/2tybuuJuqYQqDVzIUDHvVFfpXa09I1PeDVk9BsC9FuWSXoAmdHSYiQzzysOA8VNrPHNf0CtOoU9TC9Xu7bI8mFCG+8VltvOnAV44dKb9iPhMUQGXeo1VKUaVaB2jhUxELRrwuNyDGATakp4mPKoYeZFbDU11I+xhByLQXnY5gvPwprlfcnjkGywGx3se1zr2FLy1ZrFwO4shnorql+zg/0pxO7RDTc4BTCBWB10ukeHK1Xpwbx8FclW2qku+ix4A0lPTwHAhqflTNsu74hPWRu8CAHfItyxG7H55Nd5BDb95BC7eunG75imLb7ZHMER/+6W90aGnyDY8fZgGf358PhhgLBXDMrb5BE6uPfrkMkAtjWvtQSrkLmRID9F5EmkF9TICoSwrEdna2TtwXQzRQxOM9zTnOeVBFMqWIVm+HIt01wNo1mB8bIvngMg7uvtYJ0ANzpmQfpCESHucdPaWE1VuYta9eGV7a/8GOmwPK/obEVzQFfmc4kCFMglk0yuMP6EH/bWWDyb8y52ytSuVKmAPT3c+wGhlEiOhCCMblSXzkS5FiQ8AobXNCnUHumtPf/S+l1TxYiDSR+j4GHYYFmP8W//bIeNz5pmifD1DqY3wRhwDJpn9I6nCgdbnRQnNhOY2WzEQFddiEB2g5e70kcmWPk/hacUR7p+6vR8fFMaFarjdEZlrSS0DrnXwFQVuiYuJ/zARGN8gJI22WCmnGaUDTFebhvg0klLwFkBggiL
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cloudflared
