---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAy1n+Tl/CNNjB9hbJb9gv+D3lXJfef8cDTfXA+UJBXkIxCy8o9EKH7dDIR3Wfz+TobhT7NGKM+tYHDMEeho3mNP5Xl65VwLfjDnSExTzw4ySWbdIner08/vWhkHQmugcpTjkgyX7uxTfxw9sbFdXivC+LoBgozPdSLQaqo1U1VVZtPKda0941YvWyB+V1ARQO1N0wTHxcJDjv+OzICluqzUWLHTWCrl3bFJjXwGF1rsD734NBvPRetjANl3zA3IAcjMyn6xqprPfUahg/N9NOBXZhAkqTeAxNgCmiGfcQ3K3cxm4+9cLoYSTNM35gze8ZdO4D7FPlZtx76e7X+nA/kfXY8klO/T4N+nWThV3WceeXwFSXU/17BDwyoKiF0Re57Zf7SsHVvL7yNGFyZAm/b05GlZk0tHAv6zdZouOWQ2lMvyzVTKwter/JL8Qph3eXcbbDWFDzt+C1o9Tw0W11ug0jB9By/Y8r5S2izRowZB2ern1C0Mo9WyyuOOOOk6l2p2PW502rrlF1aYjDg5gRIyberb4DoagMwvBlWgeCEHuDSER065K9pai0rM3dJbueoxKJA17nUOY6EpSz59g259/0k8PX31ESu+yXeu33YUGLQE+DpIW/RL4daLT2Nqu4KmsyE4J6ImM28aPxLfs7RJhxJT/8uSCP8juB7YtujSkWUZ2dhNBRJBHJm9D3SC18y/CL6uvPa76mWBd8Ye0aO0u/LrlMnf1mMFfPvRZtpFnuO1iJWECEzNLDcMosVeoTOyHRah1km/pqLAfqGjTjQqk78tUXNyQ7JzjUkBuVF9nX2hYOdDXqioiG65b14Vb3QlTwX8dASbrPWhv17/Bq5IPV1DpFCfzrgaQBLOb65zBSqs2vzn3fayWMel1gnceFr2MJlgTV1mm9/QXfXO6llAeuC0ibhNSkXw/AVUflbYUAFy2XSKfcb
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
